// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: api/admin/v1/resources/admin_reg_email.resource.v1.proto

package adminv1

import (
	v1 "github.com/ikaiguang/go-srv-kit/api/page/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdminRegEmail ENGINE InnoDB CHARSET utf8mb4 COMMENT '管理员-注册-邮箱'
type AdminRegEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id ID
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// admin_email 管理员手机号码
	AdminEmail string `protobuf:"bytes,2,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`
	// created_time 创建时间
	CreatedTime string `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// updated_time 最后修改时间
	UpdatedTime string `protobuf:"bytes,4,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	// admin_uuid uuid
	AdminUuid string `protobuf:"bytes,5,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
}

func (x *AdminRegEmail) Reset() {
	*x = AdminRegEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegEmail) ProtoMessage() {}

func (x *AdminRegEmail) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegEmail.ProtoReflect.Descriptor instead.
func (*AdminRegEmail) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescGZIP(), []int{0}
}

func (x *AdminRegEmail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminRegEmail) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

func (x *AdminRegEmail) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *AdminRegEmail) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *AdminRegEmail) GetAdminUuid() string {
	if x != nil {
		return x.AdminUuid
	}
	return ""
}

// AdminRegEmailSaveReq save
type AdminRegEmailSaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id ID
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// admin_email 管理员手机号码
	AdminEmail string `protobuf:"bytes,2,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`
	// created_time 创建时间
	CreatedTime string `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// updated_time 最后修改时间
	UpdatedTime string `protobuf:"bytes,4,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	// admin_uuid uuid
	AdminUuid string `protobuf:"bytes,5,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
}

func (x *AdminRegEmailSaveReq) Reset() {
	*x = AdminRegEmailSaveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegEmailSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegEmailSaveReq) ProtoMessage() {}

func (x *AdminRegEmailSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegEmailSaveReq.ProtoReflect.Descriptor instead.
func (*AdminRegEmailSaveReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AdminRegEmailSaveReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminRegEmailSaveReq) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

func (x *AdminRegEmailSaveReq) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *AdminRegEmailSaveReq) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *AdminRegEmailSaveReq) GetAdminUuid() string {
	if x != nil {
		return x.AdminUuid
	}
	return ""
}

// AdminRegEmailIdReq id
type AdminRegEmailIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// admin_reg_email_id id
	AdminRegEmailId int64 `protobuf:"varint,1,opt,name=admin_reg_email_id,json=adminRegEmailId,proto3" json:"admin_reg_email_id,omitempty"`
}

func (x *AdminRegEmailIdReq) Reset() {
	*x = AdminRegEmailIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegEmailIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegEmailIdReq) ProtoMessage() {}

func (x *AdminRegEmailIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegEmailIdReq.ProtoReflect.Descriptor instead.
func (*AdminRegEmailIdReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescGZIP(), []int{2}
}

func (x *AdminRegEmailIdReq) GetAdminRegEmailId() int64 {
	if x != nil {
		return x.AdminRegEmailId
	}
	return 0
}

// AdminRegEmailIdsReq ids
type AdminRegEmailIdsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// admin_reg_email_ids ids
	AdminRegEmailIds []int64 `protobuf:"varint,1,rep,packed,name=admin_reg_email_ids,json=adminRegEmailIds,proto3" json:"admin_reg_email_ids,omitempty"`
}

func (x *AdminRegEmailIdsReq) Reset() {
	*x = AdminRegEmailIdsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegEmailIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegEmailIdsReq) ProtoMessage() {}

func (x *AdminRegEmailIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegEmailIdsReq.ProtoReflect.Descriptor instead.
func (*AdminRegEmailIdsReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescGZIP(), []int{3}
}

func (x *AdminRegEmailIdsReq) GetAdminRegEmailIds() []int64 {
	if x != nil {
		return x.AdminRegEmailIds
	}
	return nil
}

// AdminRegEmailListReq list
type AdminRegEmailListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// page_request paging request
	PageRequest *v1.PageRequest `protobuf:"bytes,1,opt,name=page_request,json=pageRequest,proto3" json:"page_request,omitempty"`
}

func (x *AdminRegEmailListReq) Reset() {
	*x = AdminRegEmailListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegEmailListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegEmailListReq) ProtoMessage() {}

func (x *AdminRegEmailListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegEmailListReq.ProtoReflect.Descriptor instead.
func (*AdminRegEmailListReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescGZIP(), []int{4}
}

func (x *AdminRegEmailListReq) GetPageRequest() *v1.PageRequest {
	if x != nil {
		return x.PageRequest
	}
	return nil
}

// AdminRegEmailListResp list
type AdminRegEmailListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// list AdminRegEmail-array
	List []*AdminRegEmail `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// page_info paging response
	PageInfo *v1.PageResponse `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
}

func (x *AdminRegEmailListResp) Reset() {
	*x = AdminRegEmailListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegEmailListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegEmailListResp) ProtoMessage() {}

func (x *AdminRegEmailListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegEmailListResp.ProtoReflect.Descriptor instead.
func (*AdminRegEmailListResp) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescGZIP(), []int{5}
}

func (x *AdminRegEmailListResp) GetList() []*AdminRegEmail {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *AdminRegEmailListResp) GetPageInfo() *v1.PageResponse {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

// AdminRegEmailProcessResult process result
type AdminRegEmailProcessResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// success true or false
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AdminRegEmailProcessResult) Reset() {
	*x = AdminRegEmailProcessResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegEmailProcessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegEmailProcessResult) ProtoMessage() {}

func (x *AdminRegEmailProcessResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegEmailProcessResult.ProtoReflect.Descriptor instead.
func (*AdminRegEmailProcessResult) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescGZIP(), []int{6}
}

func (x *AdminRegEmailProcessResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_admin_v1_resources_admin_reg_email_resource_v1_proto protoreflect.FileDescriptor

var file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDesc = []byte{
	0x0a, 0x38, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72,
	0x65, 0x67, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x76, 0x31, 0x1a,
	0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6b, 0x61, 0x69,
	0x67, 0x75, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x72, 0x76, 0x2d, 0x6b, 0x69, 0x74,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5, 0x01, 0x0a, 0x0d, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x75,
	0x69, 0x64, 0x22, 0xac, 0x01, 0x0a, 0x14, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x75, 0x69,
	0x64, 0x22, 0x41, 0x0a, 0x12, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x12, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x5f, 0x72, 0x65, 0x67, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x13, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x2d, 0x0a, 0x13, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x67, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x10, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x52,
	0x65, 0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x56, 0x0a, 0x14, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x3e, 0x0a, 0x0c, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x69, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x15, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x76, 0x31,
	0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x69, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x36, 0x0a, 0x1a, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x76, 0x31, 0x42, 0x11,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x70, 0x69, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x56,
	0x31, 0x50, 0x01, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x69, 0x6b, 0x61, 0x69, 0x67, 0x75, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x72, 0x76,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x3b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescOnce sync.Once
	file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescData = file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDesc
)

func file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescGZIP() []byte {
	file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescOnce.Do(func() {
		file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescData)
	})
	return file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDescData
}

var file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_goTypes = []interface{}{
	(*AdminRegEmail)(nil),              // 0: service.api.adminv1.AdminRegEmail
	(*AdminRegEmailSaveReq)(nil),       // 1: service.api.adminv1.AdminRegEmailSaveReq
	(*AdminRegEmailIdReq)(nil),         // 2: service.api.adminv1.AdminRegEmailIdReq
	(*AdminRegEmailIdsReq)(nil),        // 3: service.api.adminv1.AdminRegEmailIdsReq
	(*AdminRegEmailListReq)(nil),       // 4: service.api.adminv1.AdminRegEmailListReq
	(*AdminRegEmailListResp)(nil),      // 5: service.api.adminv1.AdminRegEmailListResp
	(*AdminRegEmailProcessResult)(nil), // 6: service.api.adminv1.AdminRegEmailProcessResult
	(*v1.PageRequest)(nil),             // 7: kit.api.pagev1.PageRequest
	(*v1.PageResponse)(nil),            // 8: kit.api.pagev1.PageResponse
}
var file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_depIdxs = []int32{
	7, // 0: service.api.adminv1.AdminRegEmailListReq.page_request:type_name -> kit.api.pagev1.PageRequest
	0, // 1: service.api.adminv1.AdminRegEmailListResp.list:type_name -> service.api.adminv1.AdminRegEmail
	8, // 2: service.api.adminv1.AdminRegEmailListResp.page_info:type_name -> kit.api.pagev1.PageResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_init() }
func file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_init() {
	if File_api_admin_v1_resources_admin_reg_email_resource_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegEmailSaveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegEmailIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegEmailIdsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegEmailListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegEmailListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegEmailProcessResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_goTypes,
		DependencyIndexes: file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_depIdxs,
		MessageInfos:      file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_msgTypes,
	}.Build()
	File_api_admin_v1_resources_admin_reg_email_resource_v1_proto = out.File
	file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_rawDesc = nil
	file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_goTypes = nil
	file_api_admin_v1_resources_admin_reg_email_resource_v1_proto_depIdxs = nil
}
