// Package assemblers
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package assemblers

import (
	timeutil "github.com/ikaiguang/go-srv-kit/kit/time"

	userv1 "github.com/ikaiguang/go-srv-services/api/user-service/v1/resources"
	entities "github.com/ikaiguang/go-srv-services/app/user-service/internal/domain/entity"
)

var _ = timeutil.YmdHms

// UserList assemble listUser
func (s *Assembler) UserList(dataModels []*entities.User) []*userv1.User {
	var newDataModels = make([]*userv1.User, len(dataModels))
	for index := range dataModels {
		newDataModels[index] = s.User(dataModels[index])
	}
	return newDataModels
}

// User assemble User
func (s *Assembler) User(dataModel *entities.User) *userv1.User {
	newDataModel := &userv1.User{
		Id:           dataModel.Id,                                  // ID
		UserUuid:     dataModel.UserUuid,                            // uuid
		CreatedTime:  dataModel.CreatedTime.Format(timeutil.YmdHms), // 创建时间
		UpdatedTime:  dataModel.UpdatedTime.Format(timeutil.YmdHms), // 最后修改时间
		IsDeleted:    dataModel.IsDeleted,                           // 是否已删除
		UserEmail:    dataModel.UserEmail,                           // 邮箱
		UserNickname: dataModel.UserNickname,                        // 昵称
		UserAvatar:   dataModel.UserAvatar,                          // 头像
		UserGender:   dataModel.UserGender,                          // 性别
		UserStatus:   dataModel.UserStatus,                          // 状态
		RegisterFrom: dataModel.RegisterFrom,                        // 注册来源
	}
	// DeletedTime 删除时间
	if dataModel.DeletedTime != nil {
		newDataModel.DeletedTime = dataModel.DeletedTime.Format(timeutil.YmdHms)
	}
	// ActiveBeginTime 激活开始时间
	if dataModel.ActiveBeginTime != nil {
		newDataModel.ActiveBeginTime = dataModel.ActiveBeginTime.Format(timeutil.YmdHms)
	}
	// ActiveEndTime 激活结束时间
	if dataModel.ActiveEndTime != nil {
		newDataModel.ActiveEndTime = dataModel.ActiveEndTime.Format(timeutil.YmdHms)
	}
	// DisableTime 禁用时间
	if dataModel.DisableTime != nil {
		newDataModel.DisableTime = dataModel.DisableTime.Format(timeutil.YmdHms)
	}
	// BlacklistTime 黑名单时间
	if dataModel.BlacklistTime != nil {
		newDataModel.BlacklistTime = dataModel.BlacklistTime.Format(timeutil.YmdHms)
	}

	return newDataModel
}
