// Package assemblers
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package assemblers

import (
	timeutil "github.com/ikaiguang/go-srv-kit/kit/time"

	userv1 "github.com/ikaiguang/go-srv-services/api/user/v1/resources"
	entities "github.com/ikaiguang/go-srv-services/app/user-service/internal/domain/entity"
)

var _ = timeutil.YmdHms

// AssembleListUserRegEmail assemble listUserRegEmail
func AssembleListUserRegEmail(dataModels []*entities.UserRegEmail) []*userv1.UserRegEmail {
	var newDataModels = make([]*userv1.UserRegEmail, len(dataModels))
	for index := range dataModels {
		newDataModels[index] = AssembleUserRegEmail(dataModels[index])
	}
	return newDataModels
}

// AssembleUserRegEmail assemble UserRegEmail
func AssembleUserRegEmail(dataModel *entities.UserRegEmail) *userv1.UserRegEmail {
	newDataModel := &userv1.UserRegEmail{
		Id:          dataModel.Id,                                  // ID
		UserEmail:   dataModel.UserEmail,                           // 用户手机号码
		CreatedTime: dataModel.CreatedTime.Format(timeutil.YmdHms), // 创建时间
		UpdatedTime: dataModel.UpdatedTime.Format(timeutil.YmdHms), // 最后修改时间
		UserUuid:    dataModel.UserUuid,                            // uuid
	}

	return newDataModel
}
