# app 程序
app:
  # belong_to 属于哪个项目
  belong_to: go-srv-services
  # config_type 配置类型；值：file、consul、etcd、nacos、k8s、apollo
  config_type: consul
  # name 服务名称
  name: user-service
  version: v1.0.0
  # env 开发环境；值：DEVELOP、TESTING、PREVIEW、PRODUCTION
  env: develop
  # env_branch 环境分支；main、feature/xxx、fix/xxx
  env_branch: main
  # endpoints 自定义的endpoint
  endpoints:
    - https://uufff.com
  metadata:
    id: "${app.name}_${app.env}_${app.env_branch}_${app.version}"

# base 基础
base:
  # consul 服务注册与发现
  consul:
    scheme:
    address: 127.0.0.1:8500
    path_prefix:
    datacenter:
    wait_time: 0s
    token:
    namespace:
    partition:
    with_http_basic_auth: false
    auth_username:
    auth_password:
    insecure_skip_verify: true
    tls_address:
    tls_ca_pem:
    tls_cert_pem:
    tls_key_pem:
