// Package repos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package repos

import (
	context "context"
	gormutil "github.com/ikaiguang/go-srv-kit/data/gorm"

	entities "github.com/ikaiguang/go-srv-services/app/admin-service/internal/domain/entity"
)

// AdminRegMobileRepo repo
type AdminRegMobileRepo interface {
	Create(ctx context.Context, dataModel *entities.AdminRegMobile) error
	ExistCreate(ctx context.Context, dataModel *entities.AdminRegMobile) (anotherModel *entities.AdminRegMobile, isNotFound bool, err error)
	CreateInBatches(ctx context.Context, dataModels []*entities.AdminRegMobile, batchSize int) error
	Insert(ctx context.Context, dataModels []*entities.AdminRegMobile) error
	Update(ctx context.Context, dataModel *entities.AdminRegMobile) error
	ExistUpdate(ctx context.Context, dataModel *entities.AdminRegMobile) (anotherModel *entities.AdminRegMobile, isNotFound bool, err error)
	QueryOneById(ctx context.Context, id interface{}) (dataModel *entities.AdminRegMobile, isNotFound bool, err error)
	QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *entities.AdminRegMobile, isNotFound bool, err error)
	QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) (dataModels []*entities.AdminRegMobile, err error)
	List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormutil.PaginatorArgs) (dataModels []*entities.AdminRegMobile, totalNumber int64, err error)
	Delete(ctx context.Context, dataModel *entities.AdminRegMobile) error
	DeleteByIds(ctx context.Context, ids interface{}) error
}
