// Package assemblers
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package assemblers

import (
	timeutil "github.com/ikaiguang/go-srv-kit/kit/time"

	adminv1 "github.com/ikaiguang/go-srv-services/api/admin/v1/resources"
	entities "github.com/ikaiguang/go-srv-services/app/admin-service/internal/domain/entity"
)

var _ = timeutil.YmdHms

// AssembleListAdminRegUsername assemble listAdminRegUsername
func AssembleListAdminRegUsername(dataModels []*entities.AdminRegUsername) []*adminv1.AdminRegUsername {
	var newDataModels = make([]*adminv1.AdminRegUsername, len(dataModels))
	for index := range dataModels {
		newDataModels[index] = AssembleAdminRegUsername(dataModels[index])
	}
	return newDataModels
}

// AssembleAdminRegUsername assemble AdminRegUsername
func AssembleAdminRegUsername(dataModel *entities.AdminRegUsername) *adminv1.AdminRegUsername {
	newDataModel := &adminv1.AdminRegUsername{
		Id:          dataModel.Id,                                  // ID
		UserName:    dataModel.UserName,                            // 管理员名
		CreatedTime: dataModel.CreatedTime.Format(timeutil.YmdHms), // 创建时间
		UpdatedTime: dataModel.UpdatedTime.Format(timeutil.YmdHms), // 最后修改时间
		AdminUuid:   dataModel.AdminUuid,                           // uuid
	}

	return newDataModel
}
