// Package assemblers
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package assemblers

import (
	timeutil "github.com/ikaiguang/go-srv-kit/kit/time"

	adminv1 "github.com/ikaiguang/go-srv-services/api/admin-service/v1/resources"
	entities "github.com/ikaiguang/go-srv-services/app/admin-service/internal/domain/entity"
)

var _ = timeutil.YmdHms

// AssembleListAdminRegMobile assemble listAdminRegMobile
func AssembleListAdminRegMobile(dataModels []*entities.AdminRegMobile) []*adminv1.AdminRegMobile {
	var newDataModels = make([]*adminv1.AdminRegMobile, len(dataModels))
	for index := range dataModels {
		newDataModels[index] = AssembleAdminRegMobile(dataModels[index])
	}
	return newDataModels
}

// AssembleAdminRegMobile assemble AdminRegMobile
func AssembleAdminRegMobile(dataModel *entities.AdminRegMobile) *adminv1.AdminRegMobile {
	newDataModel := &adminv1.AdminRegMobile{
		Id:          dataModel.Id,                                  // ID
		AdminMobile: dataModel.AdminMobile,                         // 管理员手机号码
		CreatedTime: dataModel.CreatedTime.Format(timeutil.YmdHms), // 创建时间
		UpdatedTime: dataModel.UpdatedTime.Format(timeutil.YmdHms), // 最后修改时间
		AdminUuid:   dataModel.AdminUuid,                           // uuid
	}

	return newDataModel
}
