// Package assemblers
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package assemblers

import (
	timeutil "github.com/ikaiguang/go-srv-kit/kit/time"
	snowflakev1 "github.com/ikaiguang/go-srv-services/api/snowflake-service/v1/resources"
	entities "github.com/ikaiguang/go-srv-services/app/snowflake-service/internal/domain/entity"
)

// Assembler ...
type Assembler struct{}

// NewAssembler ...
func NewAssembler() *Assembler {
	return &Assembler{}
}

var _ = timeutil.YmdHms

// SnowflakeNodeIDList 节点列表
func (s *Assembler) SnowflakeNodeIDList(dataModels []*entities.SnowflakeNodeID) []*snowflakev1.SnowflakeNodeID {
	var newDataModels = make([]*snowflakev1.SnowflakeNodeID, len(dataModels))
	for index := range dataModels {
		newDataModels[index] = s.SnowflakeNodeID(dataModels[index])
	}
	return newDataModels
}

// SnowflakeNodeID assemble SnowflakeNodeID
func (s *Assembler) SnowflakeNodeID(dataModel *entities.SnowflakeNodeID) *snowflakev1.SnowflakeNodeID {
	newDataModel := &snowflakev1.SnowflakeNodeID{
		Id:                   dataModel.Id,                                         // id
		InstanceExtendTime:   dataModel.InstanceExtendTime.Format(timeutil.YmdHms), // 实例续期时间
		InstanceId:           dataModel.InstanceId,                                 // 实例ID
		NodeId:               dataModel.SnowflakeNodeId,                            // 雪花算法节点id
		InstanceName:         dataModel.InstanceName,                               // 实例名称
		InstanceEndpointList: dataModel.InstanceEndpointList,                       // 实例端点数组
		InstanceMetadata:     dataModel.InstanceMetadata,                           // 实例元数据
	}
	return newDataModel
}
