// Package datas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datas

import (
	"bytes"
	context "context"
	gormutil "github.com/ikaiguang/go-srv-kit/data/gorm"
	gorm "gorm.io/gorm"
	"strings"

	entities "github.com/ikaiguang/go-srv-services/app/admin-service/internal/domain/entity"
	repos "github.com/ikaiguang/go-srv-services/app/admin-service/internal/domain/repo"
	schemas "github.com/ikaiguang/go-srv-services/app/admin-service/internal/infra/schema"
)

// adminRegUsernameRepo repo
type adminRegUsernameRepo struct {
	dbConn                 *gorm.DB                 // *gorm.DB
	AdminRegUsernameSchema schemas.AdminRegUsername // AdminRegUsername
}

// NewAdminRegUsernameRepo new data repo
func NewAdminRegUsernameRepo(dbConn *gorm.DB) repos.AdminRegUsernameRepo {
	return &adminRegUsernameRepo{
		dbConn: dbConn,
	}
}

// =============== 创建 ===============

// create insert one
func (s *adminRegUsernameRepo) create(ctx context.Context, dbConn *gorm.DB, dataModel *entities.AdminRegUsername) (err error) {
	err = dbConn.WithContext(ctx).Create(dataModel).Error
	if err != nil {
		return err
	}
	return
}

// Create insert one
func (s *adminRegUsernameRepo) Create(ctx context.Context, dataModel *entities.AdminRegUsername) error {
	return s.create(ctx, s.dbConn, dataModel)
}

// CreateWithDBConn create
func (s *adminRegUsernameRepo) CreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.AdminRegUsername) error {
	return s.create(ctx, dbConn, dataModel)
}

// existCreate exist create
func (s *adminRegUsernameRepo) existCreate(ctx context.Context, dbConn *gorm.DB, dataModel *entities.AdminRegUsername) (anotherModel *entities.AdminRegUsername, isNotFound bool, err error) {
	anotherModel = new(entities.AdminRegUsername)
	err = dbConn.WithContext(ctx).
		Table(s.AdminRegUsernameSchema.TableName()).
		Where("id = ?", dataModel.Id).
		First(anotherModel).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			isNotFound = true
			err = nil
		}
		return
	}
	return
}

// ExistCreate exist create
func (s *adminRegUsernameRepo) ExistCreate(ctx context.Context, dataModel *entities.AdminRegUsername) (anotherModel *entities.AdminRegUsername, isNotFound bool, err error) {
	return s.existCreate(ctx, s.dbConn, dataModel)
}

// ExistCreateWithDBConn exist create
func (s *adminRegUsernameRepo) ExistCreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.AdminRegUsername) (anotherModel *entities.AdminRegUsername, isNotFound bool, err error) {
	return s.existCreate(ctx, dbConn, dataModel)
}

// createInBatches create many
func (s *adminRegUsernameRepo) createInBatches(ctx context.Context, dbConn *gorm.DB, dataModels []*entities.AdminRegUsername, batchSize int) (err error) {
	err = dbConn.WithContext(ctx).CreateInBatches(dataModels, batchSize).Error
	if err != nil {
		return err
	}
	return
}

// CreateInBatches create many
func (s *adminRegUsernameRepo) CreateInBatches(ctx context.Context, dataModels []*entities.AdminRegUsername, batchSize int) error {
	return s.createInBatches(ctx, s.dbConn, dataModels, batchSize)
}

// CreateInBatchesWithDBConn create many
func (s *adminRegUsernameRepo) CreateInBatchesWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*entities.AdminRegUsername, batchSize int) error {
	return s.createInBatches(ctx, dbConn, dataModels, batchSize)
}

// =============== 更新 ===============

// update update
func (s *adminRegUsernameRepo) update(ctx context.Context, dbConn *gorm.DB, dataModel *entities.AdminRegUsername) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.AdminRegUsernameSchema.TableName()).
		Where("id = ?", dataModel.Id).
		Save(dataModel).Error
	if err != nil {
		return err
	}
	return
}

// Update update
func (s *adminRegUsernameRepo) Update(ctx context.Context, dataModel *entities.AdminRegUsername) error {
	return s.update(ctx, s.dbConn, dataModel)
}

// UpdateWithDBConn update
func (s *adminRegUsernameRepo) UpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.AdminRegUsername) error {
	return s.update(ctx, dbConn, dataModel)
}

// existUpdate exist update
func (s *adminRegUsernameRepo) existUpdate(ctx context.Context, dbConn *gorm.DB, dataModel *entities.AdminRegUsername) (anotherModel *entities.AdminRegUsername, isNotFound bool, err error) {
	anotherModel = new(entities.AdminRegUsername)
	err = dbConn.WithContext(ctx).
		Table(s.AdminRegUsernameSchema.TableName()).
		Where("id = ?", dataModel.Id).
		Where("id != ?", dataModel.Id).
		First(anotherModel).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			isNotFound = true
			err = nil
		}
		return
	}
	return
}

// ExistUpdate exist update
func (s *adminRegUsernameRepo) ExistUpdate(ctx context.Context, dataModel *entities.AdminRegUsername) (anotherModel *entities.AdminRegUsername, isNotFound bool, err error) {
	return s.existUpdate(ctx, s.dbConn, dataModel)
}

// ExistUpdateWithDBConn exist update
func (s *adminRegUsernameRepo) ExistUpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.AdminRegUsername) (anotherModel *entities.AdminRegUsername, isNotFound bool, err error) {
	return s.existUpdate(ctx, dbConn, dataModel)
}

// =============== query one : 查一个 ===============

// queryOneById query one by id
func (s *adminRegUsernameRepo) queryOneById(ctx context.Context, dbConn *gorm.DB, id interface{}) (dataModel *entities.AdminRegUsername, isNotFound bool, err error) {
	dataModel = new(entities.AdminRegUsername)
	err = dbConn.WithContext(ctx).
		Table(s.AdminRegUsernameSchema.TableName()).
		Where("id = ?", id).
		First(dataModel).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			err = nil
			isNotFound = true
		}
		return
	}
	return
}

// QueryOneById query one by id
func (s *adminRegUsernameRepo) QueryOneById(ctx context.Context, id interface{}) (dataModel *entities.AdminRegUsername, isNotFound bool, err error) {
	return s.queryOneById(ctx, s.dbConn, id)
}

// QueryOneByIdWithDBConn query one by id
func (s *adminRegUsernameRepo) QueryOneByIdWithDBConn(ctx context.Context, dbConn *gorm.DB, id interface{}) (dataModel *entities.AdminRegUsername, isNotFound bool, err error) {
	return s.queryOneById(ctx, dbConn, id)
}

// queryOneByConditions query one by conditions
func (s *adminRegUsernameRepo) queryOneByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *entities.AdminRegUsername, isNotFound bool, err error) {
	dataModel = new(entities.AdminRegUsername)
	dbConn = dbConn.WithContext(ctx).Table(s.AdminRegUsernameSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		First(dataModel).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			err = nil
			isNotFound = true
		}
		return
	}
	return
}

// QueryOneByConditions query one by conditions
func (s *adminRegUsernameRepo) QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *entities.AdminRegUsername, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, s.dbConn, conditions)
}

// QueryOneByConditionsWithDBConn query one by conditions
func (s *adminRegUsernameRepo) QueryOneByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *entities.AdminRegUsername, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, dbConn, conditions)
}

// =============== query all : 查全部 ===============

// queryAllByConditions query all by conditions
func (s *adminRegUsernameRepo) queryAllByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModels []*entities.AdminRegUsername, err error) {
	dbConn = dbConn.WithContext(ctx).Table(s.AdminRegUsernameSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		Find(&dataModels).Error
	if err != nil {
		return dataModels, err
	}
	return
}

// QueryAllByConditions query all by conditions
func (s *adminRegUsernameRepo) QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) ([]*entities.AdminRegUsername, error) {
	return s.queryAllByConditions(ctx, s.dbConn, conditions)
}

// QueryAllByConditionsWithDBConn query all by conditions
func (s *adminRegUsernameRepo) QueryAllByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) ([]*entities.AdminRegUsername, error) {
	return s.queryAllByConditions(ctx, dbConn, conditions)
}

// =============== list : 列表 ===============

// list 列表
func (s *adminRegUsernameRepo) list(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormutil.PaginatorArgs) (dataModels []*entities.AdminRegUsername, recordCount int64, err error) {
	// query where
	dbConn = dbConn.WithContext(ctx).Table(s.AdminRegUsernameSchema.TableName())
	dbConn = s.WhereConditions(dbConn, conditions)
	dbConn = gormutil.AssembleWheres(dbConn, paginatorArgs.PageWheres)

	err = dbConn.Count(&recordCount).Error
	if err != nil {
		return
	} else if recordCount == 0 {
		return // empty
	}

	// pagination
	dbConn = gormutil.AssembleOrders(dbConn, paginatorArgs.PageOrders)
	err = gormutil.Paginator(dbConn, paginatorArgs.PageOption).
		Find(&dataModels).Error
	if err != nil {
		return
	}
	return
}

// List 列表
func (s *adminRegUsernameRepo) List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormutil.PaginatorArgs) ([]*entities.AdminRegUsername, int64, error) {
	return s.list(ctx, s.dbConn, conditions, paginatorArgs)
}

// ListWithDBConn 列表
func (s *adminRegUsernameRepo) ListWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormutil.PaginatorArgs) ([]*entities.AdminRegUsername, int64, error) {
	return s.list(ctx, dbConn, conditions, paginatorArgs)
}

// =============== delete : 删除 ===============

// delete delete one
func (s *adminRegUsernameRepo) delete(ctx context.Context, dbConn *gorm.DB, dataModel *entities.AdminRegUsername) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.AdminRegUsernameSchema.TableName()).
		Where("id = ?", dataModel.Id).
		Delete(dataModel).Error
	if err != nil {
		return err
	}
	return
}

// Delete delete one
func (s *adminRegUsernameRepo) Delete(ctx context.Context, dataModel *entities.AdminRegUsername) error {
	return s.delete(ctx, s.dbConn, dataModel)
}

// DeleteWithDBConn delete one
func (s *adminRegUsernameRepo) DeleteWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *entities.AdminRegUsername) error {
	return s.delete(ctx, dbConn, dataModel)
}

// deleteByIds delete by ids
func (s *adminRegUsernameRepo) deleteByIds(ctx context.Context, dbConn *gorm.DB, ids interface{}) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.AdminRegUsernameSchema.TableName()).
		Where("id in (?)", ids).
		Delete(entities.AdminRegUsername{}).Error
	if err != nil {
		return err
	}
	return
}

// DeleteByIds delete by ids
func (s *adminRegUsernameRepo) DeleteByIds(ctx context.Context, ids interface{}) error {
	return s.deleteByIds(ctx, s.dbConn, ids)
}

// DeleteByIdsWithDBConn delete by ids
func (s *adminRegUsernameRepo) DeleteByIdsWithDBConn(ctx context.Context, dbConn *gorm.DB, ids interface{}) error {
	return s.deleteByIds(ctx, dbConn, ids)
}

// =============== insert : 批量入库 ===============

var _ gormutil.BatchInsertRepo = new(AdminRegUsernameSlice)

// AdminRegUsernameSlice 表切片
type AdminRegUsernameSlice []*entities.AdminRegUsername

// TableName 表名
func (s *AdminRegUsernameSlice) TableName() string {
	if len(*s) > 0 {
		return (*s)[0].TableName()
	}
	return (&entities.AdminRegUsername{}).TableName()
}

// Len 长度
func (s *AdminRegUsernameSlice) Len() int {
	return len(*s)
}

// InsertColumns 批量入库的列
func (s *AdminRegUsernameSlice) InsertColumns() (columnList []string, placeholder string) {
	// columns
	columnList = []string{
		"user_name", "created_time", "updated_time", "admin_uuid",
	}

	// placeholders
	insertPlaceholderBytes := bytes.Repeat([]byte("?, "), len(columnList))
	insertPlaceholderBytes = bytes.TrimSuffix(insertPlaceholderBytes, []byte(", "))

	return columnList, string(insertPlaceholderBytes)
}

// InsertValues 批量入库的值
func (s *AdminRegUsernameSlice) InsertValues(args *gormutil.BatchInsertValueArgs) (prepareData []interface{}, placeholderSlice []string) {
	dataModels := (*s)[args.StepStart:args.StepEnd]
	for index := range dataModels {
		// placeholder
		placeholderSlice = append(placeholderSlice, "("+args.InsertPlaceholder+")")

		// prepare data
		prepareData = append(prepareData, dataModels[index].UserName)
		prepareData = append(prepareData, dataModels[index].CreatedTime)
		prepareData = append(prepareData, dataModels[index].UpdatedTime)
		prepareData = append(prepareData, dataModels[index].AdminUuid)
	}
	return prepareData, placeholderSlice
}

// UpdateColumns 批量入库的列
func (s *AdminRegUsernameSlice) UpdateColumns() (columnList []string) {
	// columns
	columnList = []string{
		"user_name=excluded.user_name", "created_time=excluded.created_time", "updated_time=excluded.updated_time",
		"admin_uuid=excluded.admin_uuid",
	}
	return columnList
}

// ConflictActionForMySQL 更新冲突时的操作
func (s *AdminRegUsernameSlice) ConflictActionForMySQL() (req *gormutil.BatchInsertConflictActionReq) {
	req = &gormutil.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "AS excluded",
		OnConflictTarget:      "ON DUPLICATE KEY",
		OnConflictAction:      "UPDATE " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// ConflictActionForPostgres 更新冲突时的操作
func (s *AdminRegUsernameSlice) ConflictActionForPostgres() (req *gormutil.BatchInsertConflictActionReq) {
	req = &gormutil.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "",
		OnConflictTarget:      "ON CONFLICT(id)",
		OnConflictAction:      "DO UPDATE SET " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// insert 批量插入
func (s *adminRegUsernameRepo) insert(ctx context.Context, dbConn *gorm.DB, dataModels AdminRegUsernameSlice) error {
	return gormutil.BatchInsertWithContext(ctx, dbConn, &dataModels)
}

// Insert 批量插入
func (s *adminRegUsernameRepo) Insert(ctx context.Context, dataModels []*entities.AdminRegUsername) error {
	return s.insert(ctx, s.dbConn, dataModels)
}

// InsertWithDBConn 批量插入
func (s *adminRegUsernameRepo) InsertWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*entities.AdminRegUsername) error {
	return s.insert(ctx, dbConn, dataModels)
}

// =============== conditions : 条件 ===============

// WhereConditions orm where
func (s *adminRegUsernameRepo) WhereConditions(dbConn *gorm.DB, conditions map[string]interface{}) *gorm.DB {

	// table name
	//tableName := s.AdminRegUsernameSchema.TableName()

	// On-demand loading

	// id
	//if data, ok := conditions["id"]; ok {
	//	dbConn = dbConn.Where(tableName+".id = ?", data)
	//}

	// user_name
	//if data, ok := conditions["user_name"]; ok {
	//	dbConn = dbConn.Where(tableName+".user_name = ?", data)
	//}

	// created_time
	//if data, ok := conditions["created_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".created_time = ?", data)
	//}

	// updated_time
	//if data, ok := conditions["updated_time"]; ok {
	//	dbConn = dbConn.Where(tableName+".updated_time = ?", data)
	//}

	// admin_uuid
	//if data, ok := conditions["admin_uuid"]; ok {
	//	dbConn = dbConn.Where(tableName+".admin_uuid = ?", data)
	//}

	return dbConn
}

// UpdateColumns update columns
func (s *adminRegUsernameRepo) UpdateColumns(conditions map[string]interface{}) map[string]interface{} {

	// update columns
	updateColumns := make(map[string]interface{})

	// On-demand loading

	// id
	//if data, ok := conditions["id"]; ok {
	//	updateColumns["id"] = data
	//}

	// user_name
	//if data, ok := conditions["user_name"]; ok {
	//	updateColumns["user_name"] = data
	//}

	// created_time
	//if data, ok := conditions["created_time"]; ok {
	//	updateColumns["created_time"] = data
	//}

	// updated_time
	//if data, ok := conditions["updated_time"]; ok {
	//	updateColumns["updated_time"] = data
	//}

	// admin_uuid
	//if data, ok := conditions["admin_uuid"]; ok {
	//	updateColumns["admin_uuid"] = data
	//}

	return updateColumns
}
