// Package schemas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package schemas

import (
	migrationuitl "github.com/ikaiguang/go-srv-kit/data/migration"
	gorm "gorm.io/gorm"
	"time"
)

var _ = time.Time{}

// AdminRegEmailSchema AdminRegEmail
var AdminRegEmailSchema AdminRegEmail

// NewAdminRegEmail new schema
func NewAdminRegEmail() *AdminRegEmail {
	return &AdminRegEmail{}
}

// AdminRegEmail ENGINE InnoDB CHARSET utf8mb4 COMMENT '管理员-注册-邮箱'
type AdminRegEmail struct {
	Id          uint64    `gorm:"column:id;primaryKey;type:uint;autoIncrement;comment:ID" json:"id"`
	AdminEmail  string    `gorm:"column:admin_email;unique;type:string;size:255;not null;default:'';comment:管理员手机号码" json:"admin_email"`
	CreatedTime time.Time `gorm:"column:created_time;type:time;not null;comment:创建时间" json:"created_time"`
	UpdatedTime time.Time `gorm:"column:updated_time;type:time;not null;comment:最后修改时间" json:"updated_time"`
	AdminUuid   string    `gorm:"column:admin_uuid;unique;type:string;size:255;not null;default:'';comment:uuid" json:"admin_uuid"`
}

// TableName table name
func (s *AdminRegEmail) TableName() string {
	return "srv_admin_reg_email"
}

// CreateTableMigrator create table migrator
func (s *AdminRegEmail) CreateTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationRepo {
	return migrationuitl.NewCreateTable(migrator, s)
}

// DropTableMigrator create table migrator
func (s *AdminRegEmail) DropTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationRepo {
	return migrationuitl.NewDropTable(migrator, s)
}
