// Package schemas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package schemas

import (
	migrationutil "github.com/ikaiguang/go-srv-kit/data/migration"
	gorm "gorm.io/gorm"
	"time"
)

var _ = time.Time{}

// AdminRegMobileSchema AdminRegMobile
var AdminRegMobileSchema AdminRegMobile

// NewAdminRegMobile new schema
func NewAdminRegMobile() *AdminRegMobile {
	return &AdminRegMobile{}
}

// AdminRegMobile ENGINE InnoDB CHARSET utf8mb4 COMMENT '管理员-注册-手机号'
type AdminRegMobile struct {
	Id          uint64    `gorm:"column:id;primaryKey;type:uint;autoIncrement;comment:ID" json:"id"`
	AdminMobile string    `gorm:"column:admin_mobile;unique;type:string;size:255;not null;default:'';comment:管理员手机号码" json:"admin_mobile"`
	CreatedTime time.Time `gorm:"column:created_time;type:time;not null;comment:创建时间" json:"created_time"`
	UpdatedTime time.Time `gorm:"column:updated_time;type:time;not null;comment:最后修改时间" json:"updated_time"`
	AdminUuid   string    `gorm:"column:admin_uuid;unique;type:string;size:255;not null;default:'';comment:uuid" json:"admin_uuid"`
}

// TableName table name
func (s *AdminRegMobile) TableName() string {
	return "srv_admin_reg_mobile"
}

// CreateTableMigrator create table migrator
func (s *AdminRegMobile) CreateTableMigrator(migrator gorm.Migrator) migrationutil.MigrationInterface {
	return migrationutil.NewCreateTable(migrator, migrationutil.Version, s)
}

// DropTableMigrator create table migrator
func (s *AdminRegMobile) DropTableMigrator(migrator gorm.Migrator) migrationutil.MigrationInterface {
	return migrationutil.NewDropTable(migrator, migrationutil.Version, s)
}
