// Package schemas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package schemas

import (
	migrationutil "github.com/ikaiguang/go-srv-kit/data/migration"
	gorm "gorm.io/gorm"
	"time"
)

var _ = time.Time{}

// AdminRegUsernameSchema AdminRegUsername
var AdminRegUsernameSchema AdminRegUsername

// NewAdminRegUsername new schema
func NewAdminRegUsername() *AdminRegUsername {
	return &AdminRegUsername{}
}

// AdminRegUsername ENGINE InnoDB CHARSET utf8mb4 COMMENT '管理员-注册-用户名'
type AdminRegUsername struct {
	Id          uint64    `gorm:"column:id;primaryKey;type:uint;autoIncrement;comment:ID" json:"id"`
	UserName    string    `gorm:"column:user_name;unique;type:string;size:255;not null;default:'';comment:管理员名" json:"user_name"`
	CreatedTime time.Time `gorm:"column:created_time;type:time;not null;comment:创建时间" json:"created_time"`
	UpdatedTime time.Time `gorm:"column:updated_time;type:time;not null;comment:最后修改时间" json:"updated_time"`
	AdminUuid   string    `gorm:"column:admin_uuid;unique;type:string;size:255;not null;default:'';comment:uuid" json:"admin_uuid"`
}

// TableName table name
func (s *AdminRegUsername) TableName() string {
	return "srv_admin_reg_username"
}

// CreateTableMigrator create table migrator
func (s *AdminRegUsername) CreateTableMigrator(migrator gorm.Migrator) migrationutil.MigrationInterface {
	return migrationutil.NewCreateTable(migrator, migrationutil.Version, s)
}

// DropTableMigrator create table migrator
func (s *AdminRegUsername) DropTableMigrator(migrator gorm.Migrator) migrationutil.MigrationInterface {
	return migrationutil.NewDropTable(migrator, migrationutil.Version, s)
}
