// Package entities
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package entities

import (
	"time"
)

var _ = time.Time{}

// AdminRegMobile ENGINE InnoDB CHARSET utf8mb4 COMMENT '管理员-注册-手机号'
type AdminRegMobile struct {
	Id          uint64    `gorm:"column:id;primaryKey" json:"id"`          // ID
	AdminMobile string    `gorm:"column:admin_mobile" json:"admin_mobile"` // 管理员手机号码
	CreatedTime time.Time `gorm:"column:created_time" json:"created_time"` // 创建时间
	UpdatedTime time.Time `gorm:"column:updated_time" json:"updated_time"` // 最后修改时间
	AdminUuid   string    `gorm:"column:admin_uuid" json:"admin_uuid"`     // uuid
}

// TableName table name
func (s *AdminRegMobile) TableName() string {
	return "srv_admin_reg_mobile"
}
