// Package entities
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package entities

import (
	"time"
)

var _ = time.Time{}

// Admin ENGINE InnoDB CHARSET utf8mb4 COMMENT '管理员'
type Admin struct {
	Id              uint64     `gorm:"column:id;primaryKey" json:"id"`                    // ID
	AdminUuid       string     `gorm:"column:admin_uuid" json:"admin_uuid"`               // uuid
	CreatedTime     time.Time  `gorm:"column:created_time" json:"created_time"`           // 创建时间
	UpdatedTime     time.Time  `gorm:"column:updated_time" json:"updated_time"`           // 最后修改时间
	DeletedTime     *time.Time `gorm:"column:deleted_time" json:"deleted_time"`           // 删除时间
	IsDeleted       bool       `gorm:"column:is_deleted" json:"is_deleted"`               // 是否已删除
	AdminEmail      string     `gorm:"column:admin_email" json:"admin_email"`             // 邮箱
	AdminNickname   string     `gorm:"column:admin_nickname" json:"admin_nickname"`       // 昵称
	AdminAvatar     string     `gorm:"column:admin_avatar" json:"admin_avatar"`           // 头像
	AdminGender     string     `gorm:"column:admin_gender" json:"admin_gender"`           // 性别
	AdminStatus     string     `gorm:"column:admin_status" json:"admin_status"`           // 状态
	ActiveBeginTime *time.Time `gorm:"column:active_begin_time" json:"active_begin_time"` // 激活开始时间
	ActiveEndTime   *time.Time `gorm:"column:active_end_time" json:"active_end_time"`     // 激活结束时间
	DisableTime     *time.Time `gorm:"column:disable_time" json:"disable_time"`           // 禁用时间
	BlacklistTime   *time.Time `gorm:"column:blacklist_time" json:"blacklist_time"`       // 黑名单时间
	PasswordHash    string     `gorm:"column:password_hash" json:"password_hash"`         //密码
	RegisterFrom    string     `gorm:"column:register_from" json:"register_from"`         //注册来源
}

// TableName table name
func (s *Admin) TableName() string {
	return "srv_admin"
}
