// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: api/admin-service/v1/resources/admin_reg_username.resource.v1.proto

package adminv1

import (
	v1 "github.com/ikaiguang/go-srv-kit/api/page/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdminRegUsername ENGINE InnoDB CHARSET utf8mb4 COMMENT '管理员-注册-用户名'
type AdminRegUsername struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id ID
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// user_name 管理员名
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// created_time 创建时间
	CreatedTime string `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// updated_time 最后修改时间
	UpdatedTime string `protobuf:"bytes,4,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	// admin_uuid uuid
	AdminUuid string `protobuf:"bytes,5,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
}

func (x *AdminRegUsername) Reset() {
	*x = AdminRegUsername{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegUsername) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegUsername) ProtoMessage() {}

func (x *AdminRegUsername) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegUsername.ProtoReflect.Descriptor instead.
func (*AdminRegUsername) Descriptor() ([]byte, []int) {
	return file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescGZIP(), []int{0}
}

func (x *AdminRegUsername) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminRegUsername) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AdminRegUsername) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *AdminRegUsername) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *AdminRegUsername) GetAdminUuid() string {
	if x != nil {
		return x.AdminUuid
	}
	return ""
}

// AdminRegUsernameSaveReq save
type AdminRegUsernameSaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id ID
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// user_name 管理员名
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// created_time 创建时间
	CreatedTime string `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// updated_time 最后修改时间
	UpdatedTime string `protobuf:"bytes,4,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	// admin_uuid uuid
	AdminUuid string `protobuf:"bytes,5,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
}

func (x *AdminRegUsernameSaveReq) Reset() {
	*x = AdminRegUsernameSaveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegUsernameSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegUsernameSaveReq) ProtoMessage() {}

func (x *AdminRegUsernameSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegUsernameSaveReq.ProtoReflect.Descriptor instead.
func (*AdminRegUsernameSaveReq) Descriptor() ([]byte, []int) {
	return file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AdminRegUsernameSaveReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminRegUsernameSaveReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AdminRegUsernameSaveReq) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *AdminRegUsernameSaveReq) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *AdminRegUsernameSaveReq) GetAdminUuid() string {
	if x != nil {
		return x.AdminUuid
	}
	return ""
}

// AdminRegUsernameIdReq id
type AdminRegUsernameIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// admin_reg_username_id id
	AdminRegUsernameId int64 `protobuf:"varint,1,opt,name=admin_reg_username_id,json=adminRegUsernameId,proto3" json:"admin_reg_username_id,omitempty"`
}

func (x *AdminRegUsernameIdReq) Reset() {
	*x = AdminRegUsernameIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegUsernameIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegUsernameIdReq) ProtoMessage() {}

func (x *AdminRegUsernameIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegUsernameIdReq.ProtoReflect.Descriptor instead.
func (*AdminRegUsernameIdReq) Descriptor() ([]byte, []int) {
	return file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescGZIP(), []int{2}
}

func (x *AdminRegUsernameIdReq) GetAdminRegUsernameId() int64 {
	if x != nil {
		return x.AdminRegUsernameId
	}
	return 0
}

// AdminRegUsernameIdsReq ids
type AdminRegUsernameIdsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// admin_reg_username_ids ids
	AdminRegUsernameIds []int64 `protobuf:"varint,1,rep,packed,name=admin_reg_username_ids,json=adminRegUsernameIds,proto3" json:"admin_reg_username_ids,omitempty"`
}

func (x *AdminRegUsernameIdsReq) Reset() {
	*x = AdminRegUsernameIdsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegUsernameIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegUsernameIdsReq) ProtoMessage() {}

func (x *AdminRegUsernameIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegUsernameIdsReq.ProtoReflect.Descriptor instead.
func (*AdminRegUsernameIdsReq) Descriptor() ([]byte, []int) {
	return file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescGZIP(), []int{3}
}

func (x *AdminRegUsernameIdsReq) GetAdminRegUsernameIds() []int64 {
	if x != nil {
		return x.AdminRegUsernameIds
	}
	return nil
}

// AdminRegUsernameListReq list
type AdminRegUsernameListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// page_request paging request
	PageRequest *v1.PageRequest `protobuf:"bytes,1,opt,name=page_request,json=pageRequest,proto3" json:"page_request,omitempty"`
}

func (x *AdminRegUsernameListReq) Reset() {
	*x = AdminRegUsernameListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegUsernameListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegUsernameListReq) ProtoMessage() {}

func (x *AdminRegUsernameListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegUsernameListReq.ProtoReflect.Descriptor instead.
func (*AdminRegUsernameListReq) Descriptor() ([]byte, []int) {
	return file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescGZIP(), []int{4}
}

func (x *AdminRegUsernameListReq) GetPageRequest() *v1.PageRequest {
	if x != nil {
		return x.PageRequest
	}
	return nil
}

// AdminRegUsernameListResp list
type AdminRegUsernameListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// list AdminRegUsername-array
	List []*AdminRegUsername `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// page_info paging response
	PageInfo *v1.PageResponse `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
}

func (x *AdminRegUsernameListResp) Reset() {
	*x = AdminRegUsernameListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegUsernameListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegUsernameListResp) ProtoMessage() {}

func (x *AdminRegUsernameListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegUsernameListResp.ProtoReflect.Descriptor instead.
func (*AdminRegUsernameListResp) Descriptor() ([]byte, []int) {
	return file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescGZIP(), []int{5}
}

func (x *AdminRegUsernameListResp) GetList() []*AdminRegUsername {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *AdminRegUsernameListResp) GetPageInfo() *v1.PageResponse {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

// AdminRegUsernameProcessResult process result
type AdminRegUsernameProcessResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// success true or false
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AdminRegUsernameProcessResult) Reset() {
	*x = AdminRegUsernameProcessResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRegUsernameProcessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegUsernameProcessResult) ProtoMessage() {}

func (x *AdminRegUsernameProcessResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegUsernameProcessResult.ProtoReflect.Descriptor instead.
func (*AdminRegUsernameProcessResult) Descriptor() ([]byte, []int) {
	return file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescGZIP(), []int{6}
}

func (x *AdminRegUsernameProcessResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto protoreflect.FileDescriptor

var file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDesc = []byte{
	0x0a, 0x43, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x67, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x76, 0x31, 0x1a, 0x39, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6b, 0x61, 0x69, 0x67, 0x75, 0x61, 0x6e, 0x67,
	0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x72, 0x76, 0x2d, 0x6b, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x01, 0x0a, 0x10, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52,
	0x65, 0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x22, 0xab, 0x01, 0x0a,
	0x17, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x15, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x15, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x67,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x12, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x16, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52,
	0x65, 0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x33, 0x0a, 0x16, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x67, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x13, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x73, 0x22, 0x59, 0x0a, 0x17, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65,
	0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x3e, 0x0a, 0x0c, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x69, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x61, 0x67, 0x65, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x90, 0x01, 0x0a, 0x18, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x76,
	0x31, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x69,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x39, 0x0a, 0x1d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x77,
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x76, 0x31, 0x42, 0x11, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x70,
	0x69, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x4b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6b, 0x61, 0x69, 0x67, 0x75, 0x61, 0x6e, 0x67,
	0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x72, 0x76, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x3b,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescOnce sync.Once
	file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescData = file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDesc
)

func file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescGZIP() []byte {
	file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescOnce.Do(func() {
		file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescData)
	})
	return file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDescData
}

var file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_goTypes = []interface{}{
	(*AdminRegUsername)(nil),              // 0: service.api.adminv1.AdminRegUsername
	(*AdminRegUsernameSaveReq)(nil),       // 1: service.api.adminv1.AdminRegUsernameSaveReq
	(*AdminRegUsernameIdReq)(nil),         // 2: service.api.adminv1.AdminRegUsernameIdReq
	(*AdminRegUsernameIdsReq)(nil),        // 3: service.api.adminv1.AdminRegUsernameIdsReq
	(*AdminRegUsernameListReq)(nil),       // 4: service.api.adminv1.AdminRegUsernameListReq
	(*AdminRegUsernameListResp)(nil),      // 5: service.api.adminv1.AdminRegUsernameListResp
	(*AdminRegUsernameProcessResult)(nil), // 6: service.api.adminv1.AdminRegUsernameProcessResult
	(*v1.PageRequest)(nil),                // 7: kit.api.pagev1.PageRequest
	(*v1.PageResponse)(nil),               // 8: kit.api.pagev1.PageResponse
}
var file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_depIdxs = []int32{
	7, // 0: service.api.adminv1.AdminRegUsernameListReq.page_request:type_name -> kit.api.pagev1.PageRequest
	0, // 1: service.api.adminv1.AdminRegUsernameListResp.list:type_name -> service.api.adminv1.AdminRegUsername
	8, // 2: service.api.adminv1.AdminRegUsernameListResp.page_info:type_name -> kit.api.pagev1.PageResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_init() }
func file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_init() {
	if File_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegUsername); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegUsernameSaveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegUsernameIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegUsernameIdsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegUsernameListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegUsernameListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRegUsernameProcessResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_goTypes,
		DependencyIndexes: file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_depIdxs,
		MessageInfos:      file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_msgTypes,
	}.Build()
	File_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto = out.File
	file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_rawDesc = nil
	file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_goTypes = nil
	file_api_admin_service_v1_resources_admin_reg_username_resource_v1_proto_depIdxs = nil
}
