# app 程序
app:
  # belong_to 属于哪个项目
  belong_to: go-srv-services
  # name 服务名称
  name: user-service
  version: v1.0.0
  # env 开发环境；值：DEVELOP、TESTING、PREVIEW、PRODUCTION
  env: develop
  # env_branch 环境分支；main、feature/xxx、fix/xxx
  env_branch: main
  # endpoints 自定义的endpoint
  endpoints:
    - https://uufff.com
  metadata:
    id: "${app.name}_${app.env}_${app.env_branch}_${app.version}"

# server 服务
server:
  http:
    enable: true
    network:
    addr: 0.0.0.0:11301
    timeout: 60s
  grpc:
    enable: true
    network:
    addr: 0.0.0.0:11302
    timeout: 60s

# log 日志
log:
  console:
    enable: true
    # level 日志级别；值：DEBUG、INFO、WARN、ERROR、FATAL
    level: debug
  file:
    enable: true
    # level 日志级别；值：DEBUG、INFO、WARN、ERROR、FATAL
    level: DEBUG
    # dir: ./runtime/logs
    dir: ./runtime/logs
    filename: "${app.belong_to}_${app.name}"
    # rotate_time 轮询规则：n久(默认：86400s # 86400s = 1天)
    # 轮询规则：默认为：RotateTime
    rotate_time: 86400s
    # rotate_size 轮询规则：按文件大小(默认：52428800 # 50<<20 = 50M)
    # 轮询规则：默认为：RotateTime
    rotate_size: 52428800
    # storage_age 存储规则：n久(默认：30天)
    # 存储规则：默认为：StorageAge
    storage_age: 2592000s
    # storage_counter 存储规则：n个(默认：10086个)
    # 存储规则：默认为：StorageAge
    storage_counter: 10086
