// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/user-service/v1/services/org.service.v1.proto

package userservicev1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SrvOrgClient is the client API for SrvOrg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrvOrgClient interface {
}

type srvOrgClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvOrgClient(cc grpc.ClientConnInterface) SrvOrgClient {
	return &srvOrgClient{cc}
}

// SrvOrgServer is the server API for SrvOrg service.
// All implementations must embed UnimplementedSrvOrgServer
// for forward compatibility
type SrvOrgServer interface {
	mustEmbedUnimplementedSrvOrgServer()
}

// UnimplementedSrvOrgServer must be embedded to have forward compatible implementations.
type UnimplementedSrvOrgServer struct {
}

func (UnimplementedSrvOrgServer) mustEmbedUnimplementedSrvOrgServer() {}

// UnsafeSrvOrgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvOrgServer will
// result in compilation errors.
type UnsafeSrvOrgServer interface {
	mustEmbedUnimplementedSrvOrgServer()
}

func RegisterSrvOrgServer(s grpc.ServiceRegistrar, srv SrvOrgServer) {
	s.RegisterService(&SrvOrg_ServiceDesc, srv)
}

// SrvOrg_ServiceDesc is the grpc.ServiceDesc for SrvOrg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvOrg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.api.userservicev1.SrvOrg",
	HandlerType: (*SrvOrgServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/user-service/v1/services/org.service.v1.proto",
}
