// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: api/user-service/v1/services/user_auth.service.v1.proto

package userservicev1

import (
	context "context"
	resources "github.com/ikaiguang/go-srv-services/api/user-service/v1/resources"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SrvUserAuth_LoginByEmail_FullMethodName = "/service.api.userservicev1.SrvUserAuth/LoginByEmail"
	SrvUserAuth_Ping_FullMethodName         = "/service.api.userservicev1.SrvUserAuth/Ping"
)

// SrvUserAuthClient is the client API for SrvUserAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrvUserAuthClient interface {
	// LoginByEmail Email登录
	LoginByEmail(ctx context.Context, in *resources.LoginByEmailReq, opts ...grpc.CallOption) (*resources.LoginResp, error)
	// Ping ping pong
	Ping(ctx context.Context, in *resources.PingReq, opts ...grpc.CallOption) (*resources.PingResp, error)
}

type srvUserAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvUserAuthClient(cc grpc.ClientConnInterface) SrvUserAuthClient {
	return &srvUserAuthClient{cc}
}

func (c *srvUserAuthClient) LoginByEmail(ctx context.Context, in *resources.LoginByEmailReq, opts ...grpc.CallOption) (*resources.LoginResp, error) {
	out := new(resources.LoginResp)
	err := c.cc.Invoke(ctx, SrvUserAuth_LoginByEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvUserAuthClient) Ping(ctx context.Context, in *resources.PingReq, opts ...grpc.CallOption) (*resources.PingResp, error) {
	out := new(resources.PingResp)
	err := c.cc.Invoke(ctx, SrvUserAuth_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvUserAuthServer is the server API for SrvUserAuth service.
// All implementations must embed UnimplementedSrvUserAuthServer
// for forward compatibility
type SrvUserAuthServer interface {
	// LoginByEmail Email登录
	LoginByEmail(context.Context, *resources.LoginByEmailReq) (*resources.LoginResp, error)
	// Ping ping pong
	Ping(context.Context, *resources.PingReq) (*resources.PingResp, error)
	mustEmbedUnimplementedSrvUserAuthServer()
}

// UnimplementedSrvUserAuthServer must be embedded to have forward compatible implementations.
type UnimplementedSrvUserAuthServer struct {
}

func (UnimplementedSrvUserAuthServer) LoginByEmail(context.Context, *resources.LoginByEmailReq) (*resources.LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByEmail not implemented")
}
func (UnimplementedSrvUserAuthServer) Ping(context.Context, *resources.PingReq) (*resources.PingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSrvUserAuthServer) mustEmbedUnimplementedSrvUserAuthServer() {}

// UnsafeSrvUserAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvUserAuthServer will
// result in compilation errors.
type UnsafeSrvUserAuthServer interface {
	mustEmbedUnimplementedSrvUserAuthServer()
}

func RegisterSrvUserAuthServer(s grpc.ServiceRegistrar, srv SrvUserAuthServer) {
	s.RegisterService(&SrvUserAuth_ServiceDesc, srv)
}

func _SrvUserAuth_LoginByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.LoginByEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserAuthServer).LoginByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrvUserAuth_LoginByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserAuthServer).LoginByEmail(ctx, req.(*resources.LoginByEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvUserAuth_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvUserAuthServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrvUserAuth_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvUserAuthServer).Ping(ctx, req.(*resources.PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SrvUserAuth_ServiceDesc is the grpc.ServiceDesc for SrvUserAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvUserAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.api.userservicev1.SrvUserAuth",
	HandlerType: (*SrvUserAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginByEmail",
			Handler:    _SrvUserAuth_LoginByEmail_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _SrvUserAuth_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user-service/v1/services/user_auth.service.v1.proto",
}
